server:
  port: 8082
  servlet:
    context-path: /qq

spring:
  application:
    name: oauth2-server

#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3306/resource-content


#mybatis:
#  type-aliases-package: com.nimo.oauth2.domain
#  mapper-locations: classpath:mapper/*.xml